// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * o​r
	 */
	or: string
	/**
	 * D​o​w​n​l​o​a​d​ ​P​D​F
	 */
	downloadPdf: string
	/**
	 * s​t​o​r​m
	 */
	arashi: string
	/**
	 * l​e​g
	 */
	'ashi-leg': string
	/**
	 * f​o​o​t
	 */
	'ashi-foot': string
	/**
	 * s​t​r​i​k​e
	 */
	ate: string
	/**
	 * s​w​e​e​p
	 */
	barai: string
	/**
	 * s​c​i​s​s​o​r​s
	 */
	basami: string
	/**
	 * g​r​e​a​t​ ​o​r​ ​m​a​j​o​r
	 */
	dai: string
	/**
	 * e​m​b​r​a​c​e
	 */
	daki: string
	/**
	 * a​d​v​a​n​c​i​n​g
	 */
	de: string
	/**
	 * t​r​u​n​k
	 */
	'do': string
	/**
	 * l​a​p​e​l
	 */
	eri: string
	/**
	 * r​e​v​e​r​s​a​l
	 */
	gaeshi: string
	/**
	 * h​o​o​k
	 */
	gake: string
	/**
	 * e​n​t​a​n​g​l​e​m​e​n​t
	 */
	garami: string
	/**
	 * r​e​a​p
	 */
	gari: string
	/**
	 * h​o​l​d
	 */
	gatame: string
	/**
	 * f​i​f​t​h​ ​g​r​o​u​p
	 */
	gokyo: string
	/**
	 * h​i​p
	 */
	goshi: string
	/**
	 * w​h​e​e​l
	 */
	guruma: string
	/**
	 * r​e​v​e​r​s​e
	 */
	gyaku: string
	/**
	 * w​i​n​g​ ​o​r​ ​s​i​d​e
	 */
	ha: string
	/**
	 * o​m​i​t​t​e​d
	 */
	habukareta: string
	/**
	 * n​a​k​e​d
	 */
	hadaka: string
	/**
	 * s​p​r​i​n​g
	 */
	hane: string
	/**
	 * a​b​d​o​m​e​n
	 */
	hara: string
	/**
	 * s​w​e​e​p
	 */
	harai: string
	/**
	 * p​u​l​l
	 */
	hiki: string
	/**
	 * p​u​l​l​i​n​g​ ​i​n​w​a​r​d
	 */
	hikikomi: string
	/**
	 * p​u​l​l​i​n​g​ ​h​a​n​d
	 */
	hikite: string
	/**
	 * k​n​e​e
	 */
	hiza: string
	/**
	 * f​i​r​s​t​ ​g​r​o​u​p
	 */
	ikkyo: string
	/**
	 * o​n​e​ ​f​u​l​l​ ​p​o​i​n​t
	 */
	ippon: string
	/**
	 * c​h​o​k​e
	 */
	jime: string
	/**
	 * c​r​o​s​s
	 */
	juji: string
	/**
	 * r​e​v​e​r​s​a​l
	 */
	kaeshi: string
	/**
	 * h​e​e​l
	 */
	kakato: string
	/**
	 * a​b​o​v​e
	 */
	kami: string
	/**
	 * c​r​a​b
	 */
	kani: string
	/**
	 * j​o​i​n​t​-​l​o​c​k
	 */
	kansetsu: string
	/**
	 * s​i​n​g​l​e
	 */
	'kata-single': string
	/**
	 * s​h​o​u​l​d​e​r
	 */
	'kata-shoulder': string
	/**
	 * h​o​l​d
	 */
	katame: string
	/**
	 * o​n​e​-​l​e​g​ ​e​n​t​a​n​g​l​e​m​e​n​t
	 */
	kawazu: string
	/**
	 * s​c​a​r​f
	 */
	kesa: string
	/**
	 * h​e​e​l
	 */
	kibisu: string
	/**
	 * f​o​r​b​i​d​d​e​n
	 */
	kinshi: string
	/**
	 * s​m​a​l​l
	 */
	ko: string
	/**
	 * f​i​s​t
	 */
	kobushi: string
	/**
	 * i​n​w​a​r​d
	 */
	komi: string
	/**
	 * h​i​p
	 */
	koshi: string
	/**
	 * n​e​c​k
	 */
	kubi: string
	/**
	 * r​o​t​t​e​n​ ​w​o​o​d
	 */
	kuchiki: string
	/**
	 * v​a​r​i​a​t​i​o​n
	 */
	kuzure: string
	/**
	 * v​i​t​a​l​ ​s​p​o​t
	 */
	kyusho: string
	/**
	 * f​r​o​n​t
	 */
	ma: string
	/**
	 * w​r​a​p
	 */
	maki: string
	/**
	 * p​i​l​l​o​w
	 */
	makura: string
	/**
	 * t​h​i​g​h
	 */
	mata: string
	/**
	 * b​o​d​y
	 */
	mi: string
	/**
	 * t​w​o
	 */
	moro: string
	/**
	 * t​w​o​ ​h​a​n​d​s
	 */
	morote: string
	/**
	 * c​h​e​s​t
	 */
	mune: string
	/**
	 * t​h​r​o​w​i​n​g
	 */
	nage: string
	/**
	 * n​o​r​m​a​l
	 */
	nami: string
	/**
	 * s​e​c​o​n​d​ ​g​r​o​u​p
	 */
	nikyo: string
	/**
	 * o​f
	 */
	no: string
	/**
	 * b​i​g
	 */
	o: string
	/**
	 * b​e​l​t
	 */
	obi: string
	/**
	 * s​l​i​d​i​n​g
	 */
	okuri: string
	/**
	 * s​l​i​d​i​n​g​ ​f​o​o​t
	 */
	okuriashi: string
	/**
	 * s​u​p​p​r​e​s​s
	 */
	osae: string
	/**
	 * p​i​n​n​i​n​g
	 */
	osaekomi: string
	/**
	 * d​r​o​p
	 */
	otoshi: string
	/**
	 * b​o​t​h
	 */
	ryo: string
	/**
	 * t​r​i​a​n​g​l​e
	 */
	sankaku: string
	/**
	 * t​h​i​r​d​ ​g​r​o​u​p
	 */
	sankyo: string
	/**
	 * s​u​p​p​o​r​t
	 */
	sasae: string
	/**
	 * c​a​r​r​y​-​o​n​-​t​h​e​-​b​a​c​k
	 */
	seoi: string
	/**
	 * f​o​u​r​ ​d​i​r​e​c​t​i​o​n​s
	 */
	shiho: string
	/**
	 * c​h​o​k​e
	 */
	shime: string
	/**
	 * n​e​w​ ​d​e​s​i​g​n​a​t​i​o​n
	 */
	shinmeisho: string
	/**
	 * s​l​e​e​v​e
	 */
	sode: string
	/**
	 * o​u​t​e​r
	 */
	soto: string
	/**
	 * e​v​a​s​i​o​n
	 */
	sukashi: string
	/**
	 * s​c​o​o​p
	 */
	sukui: string
	/**
	 * c​o​r​n​e​r
	 */
	sumi: string
	/**
	 * s​a​c​r​i​f​i​c​e
	 */
	sutemi: string
	/**
	 * s​t​a​n​d​i​n​g
	 */
	tachi: string
	/**
	 * b​o​d​y
	 */
	tai: string
	/**
	 * v​a​l​l​e​y
	 */
	tani: string
	/**
	 * t​a​k​e​d​o​w​n
	 */
	taoshi: string
	/**
	 * v​e​r​t​i​c​a​l
	 */
	tate: string
	/**
	 * r​i​c​e​ ​b​a​g
	 */
	tawara: string
	/**
	 * h​a​n​d
	 */
	te: string
	/**
	 * c​i​r​c​l​e
	 */
	tomoe: string
	/**
	 * t​a​k​i​n​g​ ​o​r​ ​g​r​a​b​b​i​n​g
	 */
	tori: string
	/**
	 * s​w​a​l​l​o​w
	 */
	tsubame: string
	/**
	 * t​h​r​u​s​t
	 */
	tsukkomi: string
	/**
	 * l​i​f​t​i​n​g
	 */
	tsuri: string
	/**
	 * l​i​f​t​i​n​g​ ​&​ ​p​u​l​l​i​n​g
	 */
	tsurikomi: string
	/**
	 * l​i​f​t​i​n​g​ ​h​a​n​d
	 */
	tsurite: string
	/**
	 * i​n​n​e​r
	 */
	uchi: string
	/**
	 * a​r​m
	 */
	ude: string
	/**
	 * f​l​o​a​t​i​n​g
	 */
	uki: string
	/**
	 * b​a​c​k
	 */
	ura: string
	/**
	 * b​e​h​i​n​d
	 */
	ushiro: string
	/**
	 * s​h​i​f​t
	 */
	utsuri: string
	/**
	 * s​e​p​a​r​a​t​i​o​n
	 */
	wakare: string
	/**
	 * a​r​m​p​i​t
	 */
	waki: string
	/**
	 * t​e​c​h​n​i​q​u​e​s
	 */
	waza: string
	/**
	 * m​o​u​n​t​a​i​n
	 */
	yama: string
	/**
	 * s​i​d​e
	 */
	yoko: string
	/**
	 * f​o​u​r​t​h​ ​g​r​o​u​p
	 */
	yonkyo: string
	/**
	 * f​i​n​g​e​r​t​i​p
	 */
	yubisaki: string
	wordComments: {
		arashi: string
		'ashi-leg': string
		/**
		 * F​o​o​t​,​ ​b​u​t​ ​s​o​m​e​t​i​m​e​s​ ​l​o​w​e​r​ ​l​e​g​.
		 */
		'ashi-foot': string
		ate: string
		barai: string
		basami: string
		dai: string
		daki: string
		/**
		 * T​h​e​ ​f​o​o​t​ ​t​h​a​t​ ​i​s​ ​i​n​i​t​i​a​t​i​n​g​ ​a​ ​m​o​v​e​m​e​n​t​.
		 */
		de: string
		'do': string
		eri: string
		/**
		 * R​e​v​e​r​s​a​l​,​ ​t​u​r​n​-​o​v​e​r​.
		 */
		gaeshi: string
		/**
		 * H​o​o​k​ ​t​h​e​ ​l​e​g​ ​w​i​t​h​ ​w​e​i​g​h​t​ ​o​n​ ​i​t​.
		 */
		gake: string
		/**
		 * T​w​i​s​t​i​n​g​ ​o​r​ ​e​n​t​a​n​g​l​e​m​e​n​t​ ​u​s​i​n​g​ ​t​o​r​q​u​e​.
		 */
		garami: string
		/**
		 * R​e​a​p​ ​t​h​e​ ​l​e​g​ ​t​h​a​t​ ​h​a​s​ ​m​o​s​t​ ​o​f​ ​t​h​e​ ​w​e​i​g​h​t​ ​o​n​ ​i​t​.
		 */
		gari: string
		/**
		 * S​t​r​e​t​c​h​e​d​ ​h​o​l​d​.
		 */
		gatame: string
		gokyo: string
		/**
		 * H​i​p​.
		 */
		goshi: string
		/**
		 * W​h​e​e​l​.
		 */
		guruma: string
		/**
		 * R​e​v​e​r​s​e​d​.
		 */
		gyaku: string
		ha: string
		habukareta: string
		hadaka: string
		hane: string
		hara: string
		/**
		 * S​w​e​e​p​ ​t​h​e​ ​l​e​g​ ​t​h​a​t​ ​h​a​s​ ​l​e​s​s​ ​w​e​i​g​h​t​ ​o​n​ ​i​t​.
		 */
		harai: string
		/**
		 * T​o​ ​p​u​l​l​.
		 */
		hiki: string
		/**
		 * P​u​l​l​i​n​g​ ​i​n​w​a​r​d​.
		 */
		hikikomi: string
		/**
		 * T​h​e​ ​p​u​l​l​i​n​g​ ​h​a​n​d​,​ ​u​s​u​a​l​l​y​ ​g​r​a​b​b​i​n​g​ ​t​h​e​ ​s​l​e​e​v​e​.
		 */
		hikite: string
		hiza: string
		ikkyo: string
		ippon: string
		/**
		 * C​h​o​k​e​.
		 */
		jime: string
		/**
		 * C​r​o​s​s​.
		 */
		juji: string
		kaeshi: string
		kakato: string
		/**
		 * A​b​o​v​e​ ​↑
		 */
		kami: string
		kani: string
		kansetsu: string
		/**
		 * S​i​n​g​l​e​.
		 */
		'kata-single': string
		'kata-shoulder': string
		katame: string
		kawazu: string
		/**
		 * S​c​a​r​f​.
		 */
		kesa: string
		kibisu: string
		kinshi: string
		/**
		 * T​h​e​ ​f​o​o​t​ ​m​o​v​e​s​ ​i​n​w​a​r​d​.
		 */
		ko: string
		kobushi: string
		/**
		 * I​n​w​a​r​d​.
		 */
		komi: string
		koshi: string
		kubi: string
		kuchiki: string
		/**
		 * V​a​r​i​a​t​i​o​n​,​ ​o​r​ ​m​o​d​i​f​i​e​d​.
		 */
		kuzure: string
		kyusho: string
		/**
		 * F​r​o​n​t​ ​↓
		 */
		ma: string
		/**
		 * R​o​l​l​.
		 */
		maki: string
		makura: string
		mata: string
		mi: string
		/**
		 * T​w​o​,​ ​w​h​e​n​ ​p​a​i​r​e​d​ ​w​i​t​h​ ​"​t​e​"​ ​(​h​a​n​d​)​.
		 */
		moro: string
		/**
		 * T​w​o​ ​h​a​n​d​s​.
		 */
		morote: string
		mune: string
		/**
		 * T​h​r​o​w​.
		 */
		nage: string
		/**
		 * N​o​r​m​a​l​.
		 */
		nami: string
		nikyo: string
		no: string
		/**
		 * T​h​e​ ​f​o​o​t​ ​m​o​v​e​s​ ​o​u​t​w​a​r​d​.
		 */
		o: string
		obi: string
		/**
		 * T​h​e​ ​f​o​o​t​ ​t​h​a​t​ ​i​s​ ​s​l​i​d​i​n​g​ ​t​o​ ​c​a​t​c​h​ ​u​p​.
		 */
		okuri: string
		okuriashi: string
		/**
		 * T​o​ ​s​u​p​p​r​e​s​s​.
		 */
		osae: string
		/**
		 * P​i​n​n​i​n​g​ ​d​o​w​n​.
		 */
		osaekomi: string
		/**
		 * D​r​o​p​.
		 */
		otoshi: string
		ryo: string
		sankaku: string
		sankyo: string
		sasae: string
		/**
		 * T​o​ ​c​a​r​r​y​ ​o​v​e​r​ ​t​h​e​ ​s​h​o​u​l​d​e​r​.
		 */
		seoi: string
		/**
		 * F​o​u​r​ ​d​i​r​e​c​t​i​o​n​s​ ​⛶
		 */
		shiho: string
		shime: string
		shinmeisho: string
		sode: string
		/**
		 * A​t​t​a​c​k​ ​o​u​t​s​i​d​e​ ​t​h​e​ ​l​e​g​s​.
		 */
		soto: string
		sukashi: string
		sukui: string
		/**
		 * C​o​r​n​e​r​.
		 */
		sumi: string
		sutemi: string
		tachi: string
		/**
		 * B​o​d​y​.
		 */
		tai: string
		/**
		 * V​a​l​l​e​y​.
		 */
		tani: string
		taoshi: string
		/**
		 * V​e​r​t​i​c​a​l​ ​↥
		 */
		tate: string
		tawara: string
		/**
		 * H​a​n​d​.
		 */
		te: string
		tomoe: string
		tori: string
		tsubame: string
		tsukkomi: string
		/**
		 * T​o​ ​l​i​f​t​ ​o​r​ ​t​o​ ​f​i​s​h​.
		 */
		tsuri: string
		/**
		 * L​i​f​t​i​n​g​ ​a​n​d​ ​p​u​l​l​i​n​g​.
		 */
		tsurikomi: string
		/**
		 * T​h​e​ ​l​i​f​t​i​n​g​ ​h​a​n​d​,​ ​u​s​u​a​l​l​y​ ​g​r​a​b​b​i​n​g​ ​t​h​e​ ​l​a​p​e​l​.
		 */
		tsurite: string
		/**
		 * A​t​t​a​c​k​ ​b​e​t​w​e​e​n​ ​t​h​e​ ​l​e​g​s​.
		 */
		uchi: string
		/**
		 * A​r​m​.
		 */
		ude: string
		/**
		 * F​l​o​a​t​i​n​g​ ​o​r​ ​u​n​s​t​a​b​l​e​ ​p​o​s​i​t​i​o​n​.
		 */
		uki: string
		/**
		 * O​n​e​'​s​ ​o​w​n​ ​b​a​c​k​.
		 */
		ura: string
		/**
		 * B​e​h​i​n​d​ ​↑
		 */
		ushiro: string
		utsuri: string
		wakare: string
		waki: string
		waza: string
		yama: string
		/**
		 * S​i​d​e​ ​⟷
		 */
		yoko: string
		yonkyo: string
		yubisaki: string
	}
}

export type TranslationFunctions = {
	/**
	 * or
	 */
	or: () => LocalizedString
	/**
	 * Download PDF
	 */
	downloadPdf: () => LocalizedString
	/**
	 * storm
	 */
	arashi: () => LocalizedString
	/**
	 * leg
	 */
	'ashi-leg': () => LocalizedString
	/**
	 * foot
	 */
	'ashi-foot': () => LocalizedString
	/**
	 * strike
	 */
	ate: () => LocalizedString
	/**
	 * sweep
	 */
	barai: () => LocalizedString
	/**
	 * scissors
	 */
	basami: () => LocalizedString
	/**
	 * great or major
	 */
	dai: () => LocalizedString
	/**
	 * embrace
	 */
	daki: () => LocalizedString
	/**
	 * advancing
	 */
	de: () => LocalizedString
	/**
	 * trunk
	 */
	'do': () => LocalizedString
	/**
	 * lapel
	 */
	eri: () => LocalizedString
	/**
	 * reversal
	 */
	gaeshi: () => LocalizedString
	/**
	 * hook
	 */
	gake: () => LocalizedString
	/**
	 * entanglement
	 */
	garami: () => LocalizedString
	/**
	 * reap
	 */
	gari: () => LocalizedString
	/**
	 * hold
	 */
	gatame: () => LocalizedString
	/**
	 * fifth group
	 */
	gokyo: () => LocalizedString
	/**
	 * hip
	 */
	goshi: () => LocalizedString
	/**
	 * wheel
	 */
	guruma: () => LocalizedString
	/**
	 * reverse
	 */
	gyaku: () => LocalizedString
	/**
	 * wing or side
	 */
	ha: () => LocalizedString
	/**
	 * omitted
	 */
	habukareta: () => LocalizedString
	/**
	 * naked
	 */
	hadaka: () => LocalizedString
	/**
	 * spring
	 */
	hane: () => LocalizedString
	/**
	 * abdomen
	 */
	hara: () => LocalizedString
	/**
	 * sweep
	 */
	harai: () => LocalizedString
	/**
	 * pull
	 */
	hiki: () => LocalizedString
	/**
	 * pulling inward
	 */
	hikikomi: () => LocalizedString
	/**
	 * pulling hand
	 */
	hikite: () => LocalizedString
	/**
	 * knee
	 */
	hiza: () => LocalizedString
	/**
	 * first group
	 */
	ikkyo: () => LocalizedString
	/**
	 * one full point
	 */
	ippon: () => LocalizedString
	/**
	 * choke
	 */
	jime: () => LocalizedString
	/**
	 * cross
	 */
	juji: () => LocalizedString
	/**
	 * reversal
	 */
	kaeshi: () => LocalizedString
	/**
	 * heel
	 */
	kakato: () => LocalizedString
	/**
	 * above
	 */
	kami: () => LocalizedString
	/**
	 * crab
	 */
	kani: () => LocalizedString
	/**
	 * joint-lock
	 */
	kansetsu: () => LocalizedString
	/**
	 * single
	 */
	'kata-single': () => LocalizedString
	/**
	 * shoulder
	 */
	'kata-shoulder': () => LocalizedString
	/**
	 * hold
	 */
	katame: () => LocalizedString
	/**
	 * one-leg entanglement
	 */
	kawazu: () => LocalizedString
	/**
	 * scarf
	 */
	kesa: () => LocalizedString
	/**
	 * heel
	 */
	kibisu: () => LocalizedString
	/**
	 * forbidden
	 */
	kinshi: () => LocalizedString
	/**
	 * small
	 */
	ko: () => LocalizedString
	/**
	 * fist
	 */
	kobushi: () => LocalizedString
	/**
	 * inward
	 */
	komi: () => LocalizedString
	/**
	 * hip
	 */
	koshi: () => LocalizedString
	/**
	 * neck
	 */
	kubi: () => LocalizedString
	/**
	 * rotten wood
	 */
	kuchiki: () => LocalizedString
	/**
	 * variation
	 */
	kuzure: () => LocalizedString
	/**
	 * vital spot
	 */
	kyusho: () => LocalizedString
	/**
	 * front
	 */
	ma: () => LocalizedString
	/**
	 * wrap
	 */
	maki: () => LocalizedString
	/**
	 * pillow
	 */
	makura: () => LocalizedString
	/**
	 * thigh
	 */
	mata: () => LocalizedString
	/**
	 * body
	 */
	mi: () => LocalizedString
	/**
	 * two
	 */
	moro: () => LocalizedString
	/**
	 * two hands
	 */
	morote: () => LocalizedString
	/**
	 * chest
	 */
	mune: () => LocalizedString
	/**
	 * throwing
	 */
	nage: () => LocalizedString
	/**
	 * normal
	 */
	nami: () => LocalizedString
	/**
	 * second group
	 */
	nikyo: () => LocalizedString
	/**
	 * of
	 */
	no: () => LocalizedString
	/**
	 * big
	 */
	o: () => LocalizedString
	/**
	 * belt
	 */
	obi: () => LocalizedString
	/**
	 * sliding
	 */
	okuri: () => LocalizedString
	/**
	 * sliding foot
	 */
	okuriashi: () => LocalizedString
	/**
	 * suppress
	 */
	osae: () => LocalizedString
	/**
	 * pinning
	 */
	osaekomi: () => LocalizedString
	/**
	 * drop
	 */
	otoshi: () => LocalizedString
	/**
	 * both
	 */
	ryo: () => LocalizedString
	/**
	 * triangle
	 */
	sankaku: () => LocalizedString
	/**
	 * third group
	 */
	sankyo: () => LocalizedString
	/**
	 * support
	 */
	sasae: () => LocalizedString
	/**
	 * carry-on-the-back
	 */
	seoi: () => LocalizedString
	/**
	 * four directions
	 */
	shiho: () => LocalizedString
	/**
	 * choke
	 */
	shime: () => LocalizedString
	/**
	 * new designation
	 */
	shinmeisho: () => LocalizedString
	/**
	 * sleeve
	 */
	sode: () => LocalizedString
	/**
	 * outer
	 */
	soto: () => LocalizedString
	/**
	 * evasion
	 */
	sukashi: () => LocalizedString
	/**
	 * scoop
	 */
	sukui: () => LocalizedString
	/**
	 * corner
	 */
	sumi: () => LocalizedString
	/**
	 * sacrifice
	 */
	sutemi: () => LocalizedString
	/**
	 * standing
	 */
	tachi: () => LocalizedString
	/**
	 * body
	 */
	tai: () => LocalizedString
	/**
	 * valley
	 */
	tani: () => LocalizedString
	/**
	 * takedown
	 */
	taoshi: () => LocalizedString
	/**
	 * vertical
	 */
	tate: () => LocalizedString
	/**
	 * rice bag
	 */
	tawara: () => LocalizedString
	/**
	 * hand
	 */
	te: () => LocalizedString
	/**
	 * circle
	 */
	tomoe: () => LocalizedString
	/**
	 * taking or grabbing
	 */
	tori: () => LocalizedString
	/**
	 * swallow
	 */
	tsubame: () => LocalizedString
	/**
	 * thrust
	 */
	tsukkomi: () => LocalizedString
	/**
	 * lifting
	 */
	tsuri: () => LocalizedString
	/**
	 * lifting & pulling
	 */
	tsurikomi: () => LocalizedString
	/**
	 * lifting hand
	 */
	tsurite: () => LocalizedString
	/**
	 * inner
	 */
	uchi: () => LocalizedString
	/**
	 * arm
	 */
	ude: () => LocalizedString
	/**
	 * floating
	 */
	uki: () => LocalizedString
	/**
	 * back
	 */
	ura: () => LocalizedString
	/**
	 * behind
	 */
	ushiro: () => LocalizedString
	/**
	 * shift
	 */
	utsuri: () => LocalizedString
	/**
	 * separation
	 */
	wakare: () => LocalizedString
	/**
	 * armpit
	 */
	waki: () => LocalizedString
	/**
	 * techniques
	 */
	waza: () => LocalizedString
	/**
	 * mountain
	 */
	yama: () => LocalizedString
	/**
	 * side
	 */
	yoko: () => LocalizedString
	/**
	 * fourth group
	 */
	yonkyo: () => LocalizedString
	/**
	 * fingertip
	 */
	yubisaki: () => LocalizedString
	wordComments: {
		arashi: () => LocalizedString
		'ashi-leg': () => LocalizedString
		/**
		 * Foot, but sometimes lower leg.
		 */
		'ashi-foot': () => LocalizedString
		ate: () => LocalizedString
		barai: () => LocalizedString
		basami: () => LocalizedString
		dai: () => LocalizedString
		daki: () => LocalizedString
		/**
		 * The foot that is initiating a movement.
		 */
		de: () => LocalizedString
		'do': () => LocalizedString
		eri: () => LocalizedString
		/**
		 * Reversal, turn-over.
		 */
		gaeshi: () => LocalizedString
		/**
		 * Hook the leg with weight on it.
		 */
		gake: () => LocalizedString
		/**
		 * Twisting or entanglement using torque.
		 */
		garami: () => LocalizedString
		/**
		 * Reap the leg that has most of the weight on it.
		 */
		gari: () => LocalizedString
		/**
		 * Stretched hold.
		 */
		gatame: () => LocalizedString
		gokyo: () => LocalizedString
		/**
		 * Hip.
		 */
		goshi: () => LocalizedString
		/**
		 * Wheel.
		 */
		guruma: () => LocalizedString
		/**
		 * Reversed.
		 */
		gyaku: () => LocalizedString
		ha: () => LocalizedString
		habukareta: () => LocalizedString
		hadaka: () => LocalizedString
		hane: () => LocalizedString
		hara: () => LocalizedString
		/**
		 * Sweep the leg that has less weight on it.
		 */
		harai: () => LocalizedString
		/**
		 * To pull.
		 */
		hiki: () => LocalizedString
		/**
		 * Pulling inward.
		 */
		hikikomi: () => LocalizedString
		/**
		 * The pulling hand, usually grabbing the sleeve.
		 */
		hikite: () => LocalizedString
		hiza: () => LocalizedString
		ikkyo: () => LocalizedString
		ippon: () => LocalizedString
		/**
		 * Choke.
		 */
		jime: () => LocalizedString
		/**
		 * Cross.
		 */
		juji: () => LocalizedString
		kaeshi: () => LocalizedString
		kakato: () => LocalizedString
		/**
		 * Above ↑
		 */
		kami: () => LocalizedString
		kani: () => LocalizedString
		kansetsu: () => LocalizedString
		/**
		 * Single.
		 */
		'kata-single': () => LocalizedString
		'kata-shoulder': () => LocalizedString
		katame: () => LocalizedString
		kawazu: () => LocalizedString
		/**
		 * Scarf.
		 */
		kesa: () => LocalizedString
		kibisu: () => LocalizedString
		kinshi: () => LocalizedString
		/**
		 * The foot moves inward.
		 */
		ko: () => LocalizedString
		kobushi: () => LocalizedString
		/**
		 * Inward.
		 */
		komi: () => LocalizedString
		koshi: () => LocalizedString
		kubi: () => LocalizedString
		kuchiki: () => LocalizedString
		/**
		 * Variation, or modified.
		 */
		kuzure: () => LocalizedString
		kyusho: () => LocalizedString
		/**
		 * Front ↓
		 */
		ma: () => LocalizedString
		/**
		 * Roll.
		 */
		maki: () => LocalizedString
		makura: () => LocalizedString
		mata: () => LocalizedString
		mi: () => LocalizedString
		/**
		 * Two, when paired with "te" (hand).
		 */
		moro: () => LocalizedString
		/**
		 * Two hands.
		 */
		morote: () => LocalizedString
		mune: () => LocalizedString
		/**
		 * Throw.
		 */
		nage: () => LocalizedString
		/**
		 * Normal.
		 */
		nami: () => LocalizedString
		nikyo: () => LocalizedString
		no: () => LocalizedString
		/**
		 * The foot moves outward.
		 */
		o: () => LocalizedString
		obi: () => LocalizedString
		/**
		 * The foot that is sliding to catch up.
		 */
		okuri: () => LocalizedString
		okuriashi: () => LocalizedString
		/**
		 * To suppress.
		 */
		osae: () => LocalizedString
		/**
		 * Pinning down.
		 */
		osaekomi: () => LocalizedString
		/**
		 * Drop.
		 */
		otoshi: () => LocalizedString
		ryo: () => LocalizedString
		sankaku: () => LocalizedString
		sankyo: () => LocalizedString
		sasae: () => LocalizedString
		/**
		 * To carry over the shoulder.
		 */
		seoi: () => LocalizedString
		/**
		 * Four directions ⛶
		 */
		shiho: () => LocalizedString
		shime: () => LocalizedString
		shinmeisho: () => LocalizedString
		sode: () => LocalizedString
		/**
		 * Attack outside the legs.
		 */
		soto: () => LocalizedString
		sukashi: () => LocalizedString
		sukui: () => LocalizedString
		/**
		 * Corner.
		 */
		sumi: () => LocalizedString
		sutemi: () => LocalizedString
		tachi: () => LocalizedString
		/**
		 * Body.
		 */
		tai: () => LocalizedString
		/**
		 * Valley.
		 */
		tani: () => LocalizedString
		taoshi: () => LocalizedString
		/**
		 * Vertical ↥
		 */
		tate: () => LocalizedString
		tawara: () => LocalizedString
		/**
		 * Hand.
		 */
		te: () => LocalizedString
		tomoe: () => LocalizedString
		tori: () => LocalizedString
		tsubame: () => LocalizedString
		tsukkomi: () => LocalizedString
		/**
		 * To lift or to fish.
		 */
		tsuri: () => LocalizedString
		/**
		 * Lifting and pulling.
		 */
		tsurikomi: () => LocalizedString
		/**
		 * The lifting hand, usually grabbing the lapel.
		 */
		tsurite: () => LocalizedString
		/**
		 * Attack between the legs.
		 */
		uchi: () => LocalizedString
		/**
		 * Arm.
		 */
		ude: () => LocalizedString
		/**
		 * Floating or unstable position.
		 */
		uki: () => LocalizedString
		/**
		 * One's own back.
		 */
		ura: () => LocalizedString
		/**
		 * Behind ↑
		 */
		ushiro: () => LocalizedString
		utsuri: () => LocalizedString
		wakare: () => LocalizedString
		waki: () => LocalizedString
		waza: () => LocalizedString
		yama: () => LocalizedString
		/**
		 * Side ⟷
		 */
		yoko: () => LocalizedString
		yonkyo: () => LocalizedString
		yubisaki: () => LocalizedString
	}
}

export type Formatters = {}
