export const words = [
  { romaji: "arashi", japanese: "嵐", key: "arashi" },
  { romaji: "ashi", japanese: "脚", key: "ashi-leg" },
  { romaji: "ashi", japanese: "足", key: "ashi-foot" },
  { romaji: "ate", japanese: "当て", key: "ate" },
  { romaji: "barai", japanese: "払", key: "barai" },
  { romaji: "basami", japanese: "挟", key: "basami" },
  { romaji: "dai", japanese: "大", key: "dai" },
  { romaji: "daki", japanese: "抱", key: "daki" },
  { romaji: "de", japanese: "出", key: "de" },
  { romaji: "do", japanese: "胴", key: "do" },
  { romaji: "eri", japanese: "襟", key: "eri" },
  { romaji: "gaeshi", japanese: "返", key: "gaeshi" },
  { romaji: "gake", japanese: "掛", key: "gake" },
  { romaji: "garami", japanese: "緘", key: "garami" },
  { romaji: "gari", japanese: "刈", key: "gari" },
  { romaji: "gatame", japanese: "固", key: "gatame" },
  { romaji: "gokyo", japanese: "五教", key: "gokyo" },
  { romaji: "goshi", japanese: "腰", key: "goshi" },
  { romaji: "guruma", japanese: "車", key: "guruma" },
  { romaji: "gyaku", japanese: "逆", key: "gyaku" },
  { romaji: "ha", japanese: "羽", key: "ha" },
  { romaji: "habukareta", japanese: "省かれた", key: "habukareta" },
  { romaji: "hadaka", japanese: "裸", key: "hadaka" },
  { romaji: "hane", japanese: "跳", key: "hane" },
  { romaji: "hara", japanese: "腹", key: "hara" },
  { romaji: "harai", japanese: "払", key: "harai" },
  { romaji: "hiki", japanese: "引", key: "hiki" },
  { romaji: "hikikomi", japanese: "引込", key: "hikikomi" },
  { romaji: "hikite", japanese: "引手", key: "hikite" },
  { romaji: "hiza", japanese: "膝", key: "hiza" },
  { romaji: "ikkyo", japanese: "一教", key: "ikkyo" },
  { romaji: "ippon", japanese: "一本", key: "ippon" },
  { romaji: "jime", japanese: "絞", key: "jime" },
  { romaji: "juji", japanese: "十字", key: "juji" },
  { romaji: "kaeshi", japanese: "返", key: "kaeshi" },
  { romaji: "kakato", japanese: "踵", key: "kakato" },
  { romaji: "kami", japanese: "上", key: "kami" },
  { romaji: "kani", japanese: "蟹", key: "kani" },
  { romaji: "kansetsu", japanese: "関節", key: "kansetsu" },
  { romaji: "kata", japanese: "片", key: "kata-single" },
  { romaji: "kata", japanese: "肩", key: "kata-shoulder" },
  { romaji: "katame", japanese: "固", key: "katame" },
  { romaji: "kawazu", japanese: "河津", key: "kawazu" },
  { romaji: "kesa", japanese: "袈裟", key: "kesa" },
  { romaji: "kibisu", japanese: "踵", key: "kibisu" },
  { romaji: "kinshi", japanese: "禁止", key: "kinshi" },
  { romaji: "ko", japanese: "小", key: "ko" },
  { romaji: "kobushi", japanese: "拳", key: "kobushi" },
  { romaji: "komi", japanese: "込", key: "komi" },
  { romaji: "koshi", japanese: "腰", key: "koshi" },
  { romaji: "kubi", japanese: "首", key: "kubi" },
  { romaji: "kuchiki", japanese: "朽木", key: "kuchiki" },
  { romaji: "kuzure", japanese: "崩", key: "kuzure" },
  { romaji: "kyusho", japanese: "急所", key: "kyusho" },
  { romaji: "ma", japanese: "前", key: "ma" },
  { romaji: "maki", japanese: "巻", key: "maki" },
  { romaji: "makura", japanese: "枕", key: "makura" },
  { romaji: "mata", japanese: "股", key: "mata" },
  { romaji: "mi", japanese: "身", key: "mi" },
  { romaji: "moro", japanese: "双", key: "moro" },
  { romaji: "morote", japanese: "双手", key: "morote" },
  { romaji: "mune", japanese: "胸", key: "mune" },
  { romaji: "nage", japanese: "投げ", key: "nage" },
  { romaji: "nami", japanese: "並", key: "nami" },
  { romaji: "nikyo", japanese: "二教", key: "nikyo" },
  { romaji: "no", japanese: "の", key: "no" },
  { romaji: "o", japanese: "大", key: "o" },
  { romaji: "obi", japanese: "帯", key: "obi" },
  { romaji: "okuri", japanese: "送", key: "okuri" },
  { romaji: "okuriashi", japanese: "送足", key: "okuriashi" },
  { romaji: "osae", japanese: "抑", key: "osae" },
  { romaji: "osaekomi", japanese: "抑込", key: "osaekomi" },
  { romaji: "otoshi", japanese: "落", key: "otoshi" },
  { romaji: "ryo", japanese: "両", key: "ryo" },
  { romaji: "sankaku", japanese: "三角", key: "sankaku" },
  { romaji: "sankyo", japanese: "三教", key: "sankyo" },
  { romaji: "sasae", japanese: "支", key: "sasae" },
  { romaji: "seoi", japanese: "背負", key: "seoi" },
  { romaji: "shiho", japanese: "四方", key: "shiho" },
  { romaji: "shime", japanese: "絞", key: "shime" },
  { romaji: "shinmeisho", japanese: "新名称", key: "shinmeisho" },
  { romaji: "sode", japanese: "袖", key: "sode" },
  { romaji: "soto", japanese: "外", key: "soto" },
  { romaji: "sukashi", japanese: "透", key: "sukashi" },
  { romaji: "sukui", japanese: "掬", key: "sukui" },
  { romaji: "sumi", japanese: "隅", key: "sumi" },
  { romaji: "sutemi", japanese: "捨身", key: "sutemi" },
  { romaji: "tachi", japanese: "立ち", key: "tachi" },
  { romaji: "tai", japanese: "体", key: "tai" },
  { romaji: "tani", japanese: "谷", key: "tani" },
  { romaji: "taoshi", japanese: "倒", key: "taoshi" },
  { romaji: "tate", japanese: "縦", key: "tate" },
  { romaji: "tawara", japanese: "俵", key: "tawara" },
  { romaji: "te", japanese: "手", key: "te" },
  { romaji: "tomoe", japanese: "巴", key: "tomoe" },
  { romaji: "tori", japanese: "取", key: "tori" },
  { romaji: "tsubame", japanese: "燕", key: "tsubame" },
  { romaji: "tsukkomi", japanese: "突込", key: "tsukkomi" },
  { romaji: "tsuri", japanese: "釣", key: "tsuri" },
  { romaji: "tsurikomi", japanese: "釣込", key: "tsurikomi" },
  { romaji: "tsurite", japanese: "釣手", key: "tsurite" },
  { romaji: "uchi", japanese: "内", key: "uchi" },
  { romaji: "ude", japanese: "腕", key: "ude" },
  { romaji: "uki", japanese: "浮", key: "uki" },
  { romaji: "ura", japanese: "裏", key: "ura" },
  { romaji: "ushiro", japanese: "後", key: "ushiro" },
  { romaji: "utsuri", japanese: "移", key: "utsuri" },
  { romaji: "wakare", japanese: "分", key: "wakare" },
  { romaji: "waki", japanese: "腋", key: "waki" },
  { romaji: "waza", japanese: "技", key: "waza" },
  { romaji: "yama", japanese: "山", key: "yama" },
  { romaji: "yoko", japanese: "横", key: "yoko" },
  { romaji: "yonkyo", japanese: "四教", key: "yonkyo" },
  { romaji: "yubisaki", japanese: "指先", key: "yubisaki" },
] as const;

export type WordKey = (typeof words)[number]["key"];

export const wordsRecord = Object.fromEntries(words.map((word) => [word.key, word])) as Record<
  WordKey,
  (typeof words)[number]
>;

export const categories = [
  {
    romaji: "nage-waza",
    japanese: "投げ技",
    words: ["nage", "waza"],
  },
  {
    romaji: "te-waza",
    japanese: "手技",
    words: ["te", "waza"],
    parent: "nage-waza",
  },
  {
    romaji: "koshi-waza",
    japanese: "腰技",
    words: ["koshi", "waza"],
    parent: "nage-waza",
  },
  {
    romaji: "ashi-waza",
    japanese: "足技",
    words: ["ashi-foot", "waza"],
    parent: "nage-waza",
  },
  {
    romaji: "ma-sutemi-waza",
    japanese: "真捨身技",
    words: ["ma", "sutemi", "waza"],
    parent: "nage-waza",
  },
  {
    romaji: "yoko-sutemi-waza",
    japanese: "横捨身技",
    words: ["yoko", "sutemi", "waza"],
    parent: "nage-waza",
  },
  {
    romaji: "dai-ikkyo",
    japanese: "第一教",
    words: ["dai", "ikkyo"],
    parent: "nage-waza",
  },
  {
    romaji: "dai-nikyo",
    japanese: "第二教",
    words: ["dai", "nikyo"],
    parent: "nage-waza",
  },
  {
    romaji: "dai-sankyo",
    japanese: "第三教",
    words: ["dai", "sankyo"],
    parent: "nage-waza",
  },
  {
    romaji: "dai-yonkyo",
    japanese: "第四教",
    words: ["dai", "yonkyo"],
    parent: "nage-waza",
  },
  {
    romaji: "dai-gokyo",
    japanese: "第五教",
    words: ["dai", "gokyo"],
    parent: "nage-waza",
  },
  {
    romaji: "habukareta-waza",
    japanese: "省かれた技",
    words: ["habukareta", "waza"],
    parent: "nage-waza",
  },
  {
    romaji: "shinmeisho-no-waza",
    japanese: "新名称の技",
    words: ["shinmeisho", "waza"],
    parent: "nage-waza",
  },
  {
    romaji: "katame-waza",
    japanese: "固め技",
    words: ["katame", "waza"],
  },
  {
    romaji: "osaekomi-waza",
    japanese: "抑え込み技",
    words: ["osaekomi", "waza"],
    parent: "katame-waza",
  },
  {
    romaji: "shime-waza",
    japanese: "絞め技",
    words: ["shime", "waza"],
    parent: "katame-waza",
  },
  {
    romaji: "kansetsu-waza",
    japanese: "関節技",
    words: ["kansetsu", "waza"],
    parent: "katame-waza",
  },
  {
    romaji: "kinshi-waza",
    japanese: "禁止技",
    words: ["kinshi", "waza"],
  },
] as const satisfies {
  romaji: string;
  japanese: string;
  words: WordKey[];
  parent?: string;
}[];

export type CategoryKey = (typeof categories)[number]["romaji"];

export const waza = [
  // Dai Ikkyo (1st Group)
  {
    romaji: "deashi-harai",
    japanese: "出足払",
    words: ["de", "ashi-foot", "harai"],
    categories: ["nage-waza", "ashi-waza", "dai-ikkyo"],
    youtubeId: "4BUUvqxi_Kk",
  },
  {
    romaji: "hiza-guruma",
    japanese: "膝車",
    words: ["hiza", "guruma"],
    categories: ["nage-waza", "ashi-waza", "dai-ikkyo"],
    youtubeId: "JPJx9-oAVns",
  },
  {
    romaji: "sasae-tsurikomi-ashi",
    japanese: "支釣込足",
    words: ["sasae", "tsuri", "komi", "ashi-foot"],
    categories: ["nage-waza", "ashi-waza", "dai-ikkyo"],
    youtubeId: "699i--pvYmE",
  },
  {
    romaji: "uki-goshi",
    japanese: "浮腰",
    words: ["uki", "goshi"],
    categories: ["nage-waza", "koshi-waza", "dai-ikkyo"],
    youtubeId: "bPKwtB4lyOQ",
  },
  {
    romaji: "osoto-gari",
    japanese: "大外刈",
    words: ["o", "soto", "gari"],
    categories: ["nage-waza", "ashi-waza", "dai-ikkyo"],
    youtubeId: "c-A_nP7mKAc",
  },
  {
    romaji: "o-goshi",
    japanese: "大腰",
    words: ["o", "goshi"],
    categories: ["nage-waza", "koshi-waza", "dai-ikkyo"],
    youtubeId: "yhu1mfy2vJ4",
  },
  {
    romaji: "ouchi-gari",
    japanese: "大内刈",
    words: ["o", "uchi", "gari"],
    categories: ["nage-waza", "ashi-waza", "dai-ikkyo"],
    youtubeId: "0itJFhV9pDQ",
  },
  {
    romaji: "seoi-nage",
    japanese: "背負投",
    words: ["seoi", "nage"],
    categories: ["nage-waza", "te-waza", "dai-ikkyo"],
    youtubeId: "zIq0xI0ogxk",
  },

  // Dai Nikyo (2nd Group)
  {
    romaji: "kosoto-gari",
    japanese: "小外刈",
    words: ["ko", "soto", "gari"],
    categories: ["nage-waza", "ashi-waza", "dai-nikyo"],
    youtubeId: "jeQ541ScLB4",
  },
  {
    romaji: "kouchi-gari",
    japanese: "小内刈",
    words: ["ko", "uchi", "gari"],
    categories: ["nage-waza", "ashi-waza", "dai-nikyo"],
    youtubeId: "3Jb3tZvr9Ng",
  },
  {
    romaji: "koshi-guruma",
    japanese: "腰車",
    words: ["koshi", "guruma"],
    categories: ["nage-waza", "koshi-waza", "dai-nikyo"],
    youtubeId: "SU7Id6uVJ44",
  },
  {
    romaji: "tsurikomi-goshi",
    japanese: "釣込腰",
    words: ["tsuri", "komi", "goshi"],
    categories: ["nage-waza", "koshi-waza", "dai-nikyo"],
    youtubeId: "McfzA0yRVt4",
  },
  {
    romaji: "okuriashi-harai",
    japanese: "送足払",
    words: ["okuri", "ashi-foot", "harai"],
    categories: ["nage-waza", "ashi-waza", "dai-nikyo"],
    youtubeId: "nw1ZdRjrdRI",
  },
  {
    romaji: "tai-otoshi",
    japanese: "体落",
    words: ["tai", "otoshi"],
    categories: ["nage-waza", "te-waza", "dai-nikyo"],
    youtubeId: "4x6S3Q-Ktv8",
  },
  {
    romaji: "harai-goshi",
    japanese: "払腰",
    words: ["harai", "goshi"],
    categories: ["nage-waza", "koshi-waza", "dai-nikyo"],
    youtubeId: "qTo8HlAAkOo",
  },
  {
    romaji: "uchi-mata",
    japanese: "内股",
    words: ["uchi", "mata"],
    categories: ["nage-waza", "ashi-waza", "dai-nikyo"],
    youtubeId: "iUpSu5J-bgw",
  },

  // Dai Sankyo (3rd Group)
  {
    romaji: "kosoto-gake",
    japanese: "小外掛",
    words: ["ko", "soto", "gake"],
    categories: ["nage-waza", "ashi-waza", "dai-sankyo"],
    youtubeId: "8b6kY4s4zH4",
  },
  {
    youtubeId: "",
    romaji: "tsuri-goshi",
    japanese: "釣腰",
    words: ["tsuri", "goshi"],
    categories: ["nage-waza", "koshi-waza", "dai-sankyo"],
  },
  {
    romaji: "yoko-otoshi",
    japanese: "横落",
    words: ["yoko", "otoshi"],
    categories: ["nage-waza", "yoko-sutemi-waza", "dai-sankyo"],
    youtubeId: "MnNG67pF_a0",
  },
  {
    romaji: "ashi-guruma",
    japanese: "足車",
    words: ["ashi-foot", "guruma"],
    categories: ["nage-waza", "ashi-waza", "dai-sankyo"],
    youtubeId: "ROeayhvom9U",
  },
  {
    romaji: "hane-goshi",
    japanese: "跳腰",
    words: ["hane", "goshi"],
    categories: ["nage-waza", "koshi-waza", "dai-sankyo"],
    youtubeId: "M9_7De6A1kk",
  },
  {
    romaji: "harai-tsurikomi-ashi",
    japanese: "払釣込足",
    words: ["harai", "tsuri", "komi", "ashi-foot"],
    categories: ["nage-waza", "ashi-waza", "dai-sankyo"],
    youtubeId: "gGPXvWL8VbE",
  },
  {
    romaji: "tomoe-nage",
    japanese: "巴投",
    words: ["tomoe", "nage"],
    categories: ["nage-waza", "ma-sutemi-waza", "dai-sankyo"],
    youtubeId: "880WbHvHv6A",
  },
  {
    romaji: "kata-guruma",
    japanese: "肩車",
    words: ["kata-shoulder", "guruma"],
    categories: ["nage-waza", "te-waza", "dai-sankyo"],
    youtubeId: "cnHRhSy8yi4",
  },

  // Dai Yonkyo (4th Group)
  {
    romaji: "sumi-gaeshi",
    japanese: "隅返",
    words: ["sumi", "gaeshi"],
    categories: ["nage-waza", "ma-sutemi-waza", "dai-yonkyo"],
    youtubeId: "5VhduA5xkbA",
  },
  {
    romaji: "tani-otoshi",
    japanese: "谷落",
    words: ["tani", "otoshi"],
    categories: ["nage-waza", "yoko-sutemi-waza", "dai-yonkyo"],
    youtubeId: "3b9Me3Fohpk",
  },
  {
    romaji: "hane-makikomi",
    japanese: "跳巻込",
    words: ["hane", "maki", "komi"],
    categories: ["nage-waza", "yoko-sutemi-waza", "dai-yonkyo"],
    youtubeId: "6CRBGLGz9j8",
  },
  {
    romaji: "sukui-nage",
    japanese: "掬投",
    words: ["sukui", "nage"],
    categories: ["nage-waza", "te-waza", "dai-yonkyo"],
    youtubeId: "vU6aJ2kFxoI",
  },
  {
    romaji: "utsuri-goshi",
    japanese: "移腰",
    words: ["utsuri", "goshi"],
    categories: ["nage-waza", "koshi-waza", "dai-yonkyo"],
    youtubeId: "4pQd_bEnlf0",
  },
  {
    romaji: "o-guruma",
    japanese: "大車",
    words: ["o", "guruma"],
    categories: ["nage-waza", "ashi-waza", "dai-yonkyo"],
    youtubeId: "SnZciTAY9vc",
  },
  {
    romaji: "soto-makikomi",
    japanese: "外巻込",
    words: ["soto", "maki", "komi"],
    categories: ["nage-waza", "yoko-sutemi-waza", "dai-yonkyo"],
    youtubeId: "bWG9O1BVKtQ",
  },
  {
    romaji: "uki-otoshi",
    japanese: "浮落",
    words: ["uki", "otoshi"],
    categories: ["nage-waza", "te-waza", "dai-yonkyo"],
    youtubeId: "6H5tmncOY4Q",
  },

  // Dai Gokyo (5th Group)
  {
    romaji: "osoto-guruma",
    japanese: "大外車",
    words: ["o", "soto", "guruma"],
    categories: ["nage-waza", "ashi-waza", "dai-gokyo"],
    youtubeId: "92KbCm6pQeI",
  },
  {
    romaji: "uki-waza",
    japanese: "浮技",
    words: ["uki", "waza"],
    categories: ["nage-waza", "yoko-sutemi-waza", "dai-gokyo"],
    youtubeId: "weVOpJ63gII",
  },
  {
    romaji: "yoko-wakare",
    japanese: "横分",
    words: ["yoko", "wakare"],
    categories: ["nage-waza", "yoko-sutemi-waza", "dai-gokyo"],
    youtubeId: "bp1tscHlePI",
  },
  {
    romaji: "yoko-guruma",
    japanese: "横車",
    words: ["yoko", "guruma"],
    categories: ["nage-waza", "yoko-sutemi-waza", "dai-gokyo"],
    youtubeId: "MehP6I5cY2c",
  },
  {
    romaji: "ushiro-goshi",
    japanese: "後腰",
    words: ["ushiro", "goshi"],
    categories: ["nage-waza", "koshi-waza", "dai-gokyo"],
    youtubeId: "ORIYstuxYT8",
  },
  {
    romaji: "ura-nage",
    japanese: "裏投",
    words: ["ura", "nage"],
    categories: ["nage-waza", "ma-sutemi-waza", "dai-gokyo"],
    youtubeId: "Fgi9b8DJ5sQ",
  },
  {
    romaji: "sumi-otoshi",
    japanese: "隅落",
    words: ["sumi", "otoshi"],
    categories: ["nage-waza", "te-waza", "dai-gokyo"],
    youtubeId: "lLU9wv52ni0",
  },
  {
    romaji: "yoko-gake",
    japanese: "横掛",
    words: ["yoko", "gake"],
    categories: ["nage-waza", "yoko-sutemi-waza", "dai-gokyo"],
    youtubeId: "tP1Sj1uDfSo",
  },

  // Habukareta Waza
  {
    romaji: "obi-otoshi",
    japanese: "帯落",
    words: ["obi", "otoshi"],
    categories: ["nage-waza", "te-waza", "habukareta-waza"],
    youtubeId: "ff8U2TVZIYI",
  },
  {
    romaji: "seoi-otoshi",
    japanese: "背負落",
    words: ["seoi", "otoshi"],
    categories: ["nage-waza", "te-waza", "habukareta-waza"],
    youtubeId: "vu1TMVNnq34",
  },
  {
    romaji: "yama-arashi",
    japanese: "山嵐",
    words: ["yama", "arashi"],
    categories: ["nage-waza", "habukareta-waza"],
    youtubeId: "MGlyKmSuzdc",
  },
  {
    romaji: "osoto-otoshi",
    japanese: "大外落",
    words: ["o", "soto", "otoshi"],
    categories: ["nage-waza", "ashi-waza", "habukareta-waza"],
    youtubeId: "2DsVvDw7b8g",
  },
  {
    romaji: "daki-wakare",
    japanese: "抱分",
    words: ["daki", "wakare"],
    categories: ["nage-waza", "yoko-sutemi-waza", "habukareta-waza"],
    youtubeId: "Hr0cOMGBDYo",
  },
  {
    romaji: "hikikomi-gaeshi",
    japanese: "引込返",
    words: ["hiki", "komi", "gaeshi"],
    categories: ["nage-waza", "ma-sutemi-waza", "habukareta-waza"],
    youtubeId: "92zUYWBp5N8",
  },
  {
    romaji: "tawara-gaeshi",
    japanese: "俵返",
    words: ["tawara", "gaeshi"],
    categories: ["nage-waza", "ma-sutemi-waza", "habukareta-waza"],
    youtubeId: "TmTWgrmViZc",
  },
  {
    romaji: "uchi-makikomi",
    japanese: "内巻込",
    words: ["uchi", "maki", "komi"],
    categories: ["nage-waza", "yoko-sutemi-waza", "habukareta-waza"],
    youtubeId: "5BowcjduxVc",
  },

  // Shinmeisho No Waza
  {
    romaji: "morote-gari",
    japanese: "双手刈",
    words: ["morote", "gari"],
    categories: ["nage-waza", "te-waza", "shinmeisho-no-waza"],
    youtubeId: "BHLQS4K85bs",
  },
  {
    romaji: "kuchiki-taoshi",
    japanese: "朽木倒",
    words: ["kuchiki", "taoshi"],
    categories: ["nage-waza", "te-waza", "shinmeisho-no-waza"],
    youtubeId: "ZNL47q1aJNY",
  },
  {
    romaji: "kibisu-gaeshi",
    japanese: "踵返",
    words: ["kibisu", "gaeshi"],
    categories: ["nage-waza", "ashi-waza", "shinmeisho-no-waza"],
    youtubeId: "tJylJYfBliA",
  },
  {
    romaji: "uchi-mata-sukashi",
    japanese: "内股透",
    words: ["uchi", "mata", "sukashi"],
    categories: ["nage-waza", "ashi-waza", "shinmeisho-no-waza"],
    youtubeId: "V-RS3uhtVWM",
  },
  {
    romaji: "tsubame-gaeshi",
    japanese: "燕返",
    words: ["tsubame", "gaeshi"],
    categories: ["nage-waza", "ashi-waza", "shinmeisho-no-waza"],
    youtubeId: "GwweWqqFB5g",
  },
  {
    romaji: "kouchi-gaeshi",
    japanese: "小内返",
    words: ["ko", "uchi", "gaeshi"],
    categories: ["nage-waza", "ashi-waza", "shinmeisho-no-waza"],
    youtubeId: "_MWAdYi_LC4",
  },
  {
    romaji: "ouchi-gaeshi",
    japanese: "大内返",
    words: ["o", "uchi", "gaeshi"],
    categories: ["nage-waza", "ashi-waza", "shinmeisho-no-waza"],
    youtubeId: "dCyZTXyjIXE",
  },
  {
    romaji: "osoto-gaeshi",
    japanese: "大外返",
    words: ["o", "soto", "gaeshi"],
    categories: ["nage-waza", "ashi-waza", "shinmeisho-no-waza"],
    youtubeId: "8ZjM3X_EANo",
  },
  {
    romaji: "harai-goshi-gaeshi",
    japanese: "払腰返",
    words: ["harai", "goshi", "gaeshi"],
    categories: ["nage-waza", "koshi-waza", "shinmeisho-no-waza"],
    youtubeId: "4U3It-7PPsc",
  },
  {
    romaji: "uchi-mata-gaeshi",
    japanese: "内股返",
    words: ["uchi", "mata", "gaeshi"],
    categories: ["nage-waza", "ashi-waza", "shinmeisho-no-waza"],
    youtubeId: "Sy6sLWxkWYw",
  },
  {
    romaji: "hane-goshi-gaeshi",
    japanese: "跳腰返",
    words: ["hane", "goshi", "gaeshi"],
    categories: ["nage-waza", "koshi-waza", "shinmeisho-no-waza"],
    youtubeId: "9bZAZSBtnGs",
  },
  {
    romaji: "kani-basami",
    japanese: "蟹挟",
    words: ["kani", "basami"],
    categories: ["nage-waza", "kinshi-waza", "shinmeisho-no-waza"],
    youtubeId: "OR-HGHnarYc",
  },
  {
    romaji: "osoto-makikomi",
    japanese: "大外巻込",
    words: ["o", "soto", "maki", "komi"],
    categories: ["nage-waza", "yoko-sutemi-waza", "shinmeisho-no-waza"],
    youtubeId: "DGDv2oMwmas",
  },
  {
    romaji: "kawazu-gake",
    japanese: "河津掛",
    words: ["kawazu", "gake"],
    categories: ["nage-waza", "kinshi-waza", "shinmeisho-no-waza"],
    youtubeId: "w6G57bWACi0",
  },
  {
    romaji: "harai-makikomi",
    japanese: "払巻込",
    words: ["harai", "maki", "komi"],
    categories: ["nage-waza", "yoko-sutemi-waza", "shinmeisho-no-waza"],
    youtubeId: "VBaHzKaCXss",
  },
  {
    romaji: "uchi-mata-makikomi",
    japanese: "内股巻込",
    words: ["uchi", "mata", "maki", "komi"],
    categories: ["nage-waza", "yoko-sutemi-waza", "shinmeisho-no-waza"],
    youtubeId: "jZXENTLpJCI",
  },
  {
    romaji: "sode-tsurikomi-goshi",
    japanese: "袖釣込腰",
    words: ["sode", "tsuri", "komi", "goshi"],
    categories: ["nage-waza", "koshi-waza", "shinmeisho-no-waza"],
    youtubeId: "QsmAxpmYLOI",
  },
  {
    romaji: "ippon-seoi-nage",
    japanese: "一本背負投",
    words: ["ippon", "seoi", "nage"],
    categories: ["nage-waza", "te-waza", "shinmeisho-no-waza"],
    youtubeId: "FQnOlCxo4oI",
  },
  {
    romaji: "obi-tori-gaeshi",
    japanese: "帯取返",
    words: ["obi", "tori", "gaeshi"],
    categories: ["nage-waza", "te-waza", "shinmeisho-no-waza"],
    youtubeId: "bpc82SrunUU",
  },
  {
    romaji: "kouchi-makikomi",
    japanese: "小内巻込",
    words: ["ko", "uchi", "maki", "komi"],
    categories: ["nage-waza", "yoko-sutemi-waza", "shinmeisho-no-waza"],
    youtubeId: "_1eygIXLD_w",
  },

  // Osaekomi-waza (Pins)
  {
    romaji: "kesa-gatame",
    japanese: "袈裟固",
    words: ["kesa", "gatame"],
    categories: ["katame-waza", "osaekomi-waza"],
    youtubeId: "NDaQuJOFBYk",
  },
  {
    romaji: "kata-gatame",
    japanese: "肩固",
    words: ["kata-shoulder", "gatame"],
    categories: ["katame-waza", "osaekomi-waza"],
    youtubeId: "zQR3IOXxO_Q",
  },
  {
    romaji: "kami-shiho-gatame",
    japanese: "上四方固",
    words: ["kami", "shiho", "gatame"],
    categories: ["katame-waza", "osaekomi-waza"],
    youtubeId: "HFuMjOv0WN8",
  },
  {
    romaji: "kuzure-kami-shiho-gatame",
    japanese: "崩上四方固",
    words: ["kuzure", "kami", "shiho", "gatame"],
    categories: ["katame-waza", "osaekomi-waza"],
    youtubeId: "YUrogQWdwiY",
  },
  {
    romaji: "yoko-shiho-gatame",
    japanese: "横四方固",
    words: ["yoko", "shiho", "gatame"],
    categories: ["katame-waza", "osaekomi-waza"],
    youtubeId: "TT7XJVSEQxA",
  },
  {
    romaji: "tate-shiho-gatame",
    japanese: "縦四方固",
    words: ["tate", "shiho", "gatame"],
    categories: ["katame-waza", "osaekomi-waza"],
    youtubeId: "55-rFmBx53g",
  },
  {
    romaji: "kuzure-kesa-gatame",
    japanese: "崩袈裟固",
    words: ["kuzure", "kesa", "gatame"],
    categories: ["katame-waza", "osaekomi-waza"],
    youtubeId: "Q2fb9jaoUFQ",
  },
  {
    romaji: "uki-gatame",
    japanese: "浮固",
    words: ["uki", "gatame"],
    categories: ["katame-waza", "osaekomi-waza"],
    youtubeId: "e_lAjik1SUM",
  },
  {
    romaji: "ura-gatame",
    japanese: "裏固",
    words: ["ura", "gatame"],
    categories: ["katame-waza", "osaekomi-waza"],
    youtubeId: "eeAHZB0v3XY",
  },
  {
    romaji: "ushiro-kesa-gatame",
    japanese: "後袈裟固",
    words: ["ushiro", "kesa", "gatame"],
    categories: ["katame-waza", "osaekomi-waza"],
    youtubeId: "SBapox2M2dE",
  },

  // Shime-waza (Chokes)
  {
    romaji: "nami-juji-jime",
    japanese: "並十字絞",
    words: ["nami", "juji", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "k2cHry9HByQ",
  },
  {
    romaji: "gyaku-juji-jime",
    japanese: "逆十字絞",
    words: ["gyaku", "juji", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "t3tQriIPdlI",
  },
  {
    romaji: "kata-juji-jime",
    japanese: "片十字絞",
    words: ["kata-single", "juji", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "3VZVUAmiMD8",
  },
  {
    romaji: "hadaka-jime",
    japanese: "裸絞",
    words: ["hadaka", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "9f0n8jez7iA",
  },
  {
    romaji: "okuri-eri-jime",
    japanese: "送襟絞",
    words: ["okuri", "eri", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "EiqyoVcIAi8",
  },
  {
    romaji: "kata-ha-jime",
    japanese: "片羽絞",
    words: ["kata-single", "ha", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "yaTGgRjnwB8",
  },
  {
    romaji: "do-jime",
    japanese: "胴絞",
    words: ["do", "jime"],
    categories: ["katame-waza", "shime-waza", "kinshi-waza"],
    youtubeId: "D_0fFcoIbvY",
  },
  {
    romaji: "sode-guruma-jime",
    japanese: "袖車絞",
    words: ["sode", "guruma", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "E3nvQzClcAU",
  },
  {
    romaji: "kata-te-jime",
    japanese: "片手絞",
    words: ["kata-single", "te", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "cHeIs-fSqwE",
  },
  {
    romaji: "ryo-te-jime",
    japanese: "両手絞",
    words: ["ryo", "te", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "-RHC4V7TQiY",
  },
  {
    romaji: "tsukkomi-jime",
    japanese: "突込絞",
    words: ["tsukkomi", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "dKKpnD3eLcY",
  },
  {
    romaji: "sankaku-jime",
    japanese: "三角絞",
    words: ["sankaku", "jime"],
    categories: ["katame-waza", "shime-waza"],
    youtubeId: "lq1CUBRAm7s",
  },

  // Kansetsu-waza (Joint Locks)
  {
    romaji: "ude-garami",
    japanese: "腕緘",
    words: ["ude", "garami"],
    categories: ["katame-waza", "kansetsu-waza"],
    youtubeId: "AIlTvZb4RlE",
  },
  {
    romaji: "juji-gatame",
    japanese: "十字固",
    words: ["juji", "gatame"],
    categories: ["katame-waza", "kansetsu-waza"],
    youtubeId: "OWgSOlCuMXw",
  },
  {
    romaji: "ude-gatame",
    japanese: "腕固",
    words: ["ude", "gatame"],
    categories: ["katame-waza", "kansetsu-waza"],
    youtubeId: "SBf0aTma1VI",
  },
  {
    romaji: "hiza-gatame",
    japanese: "膝固",
    words: ["hiza", "gatame"],
    categories: ["katame-waza", "kansetsu-waza"],
    youtubeId: "H2HtAJdiJcE",
  },
  {
    romaji: "waki-gatame",
    japanese: "腋固",
    words: ["waki", "gatame"],
    categories: ["katame-waza", "kansetsu-waza"],
    youtubeId: "8F5p1zuJRG0",
  },
  {
    romaji: "hara-gatame",
    japanese: "腹固",
    words: ["hara", "gatame"],
    categories: ["katame-waza", "kansetsu-waza"],
    youtubeId: "ZzEycg8R_9M",
  },
  {
    romaji: "ashi-garami",
    japanese: "足緘",
    words: ["ashi-foot", "garami"],
    categories: ["katame-waza", "kansetsu-waza", "kinshi-waza"],
    youtubeId: "BWWb0GoAtZw",
  },
  {
    romaji: "ashi-gatame",
    japanese: "脚固",
    words: ["ashi-leg", "gatame"],
    categories: ["katame-waza", "kansetsu-waza"],
    youtubeId: "ClY7g_pX-4s",
  },
  {
    romaji: "te-gatame",
    japanese: "手固",
    words: ["te", "gatame"],
    categories: ["katame-waza", "kansetsu-waza"],
    youtubeId: "6DnvhY0tQVM",
  },
  {
    romaji: "sankaku-gatame",
    japanese: "三角固",
    words: ["sankaku", "gatame"],
    categories: ["katame-waza", "kansetsu-waza"],
    youtubeId: "WefAmW4azhk",
  },
] as const satisfies {
  romaji: string;
  japanese: string;
  words: WordKey[];
  categories: CategoryKey[];
  youtubeId: string;
}[];

export type WazaKey = (typeof waza)[number]["romaji"];

export const wazaRecord = Object.fromEntries(waza.map((waza) => [waza.romaji, waza])) as Record<
  WazaKey,
  (typeof waza)[number]
>;
